/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PDotjsRouteImport } from './routes/p[.]js'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitesIndexRouteImport } from './routes/sites.index'
import { Route as SitesNewRouteImport } from './routes/sites.new'
import { Route as SitesSiteIdRouteImport } from './routes/sites.$siteId'
import { Route as ApiPublicCollectRouteImport } from './routes/api/public/collect'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PDotjsRoute = PDotjsRouteImport.update({
  id: '/p.js',
  path: '/p.js',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesIndexRoute = SitesIndexRouteImport.update({
  id: '/sites/',
  path: '/sites/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesNewRoute = SitesNewRouteImport.update({
  id: '/sites/new',
  path: '/sites/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesSiteIdRoute = SitesSiteIdRouteImport.update({
  id: '/sites/$siteId',
  path: '/sites/$siteId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCollectRoute = ApiPublicCollectRouteImport.update({
  id: '/api/public/collect',
  path: '/api/public/collect',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/p.js': typeof PDotjsRoute
  '/settings': typeof SettingsRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/sites/new': typeof SitesNewRoute
  '/sites/': typeof SitesIndexRoute
  '/api/public/collect': typeof ApiPublicCollectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/p.js': typeof PDotjsRoute
  '/settings': typeof SettingsRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/sites/new': typeof SitesNewRoute
  '/sites': typeof SitesIndexRoute
  '/api/public/collect': typeof ApiPublicCollectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/p.js': typeof PDotjsRoute
  '/settings': typeof SettingsRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/sites/new': typeof SitesNewRoute
  '/sites/': typeof SitesIndexRoute
  '/api/public/collect': typeof ApiPublicCollectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/p.js'
    | '/settings'
    | '/sites/$siteId'
    | '/sites/new'
    | '/sites/'
    | '/api/public/collect'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/p.js'
    | '/settings'
    | '/sites/$siteId'
    | '/sites/new'
    | '/sites'
    | '/api/public/collect'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/p.js'
    | '/settings'
    | '/sites/$siteId'
    | '/sites/new'
    | '/sites/'
    | '/api/public/collect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  PDotjsRoute: typeof PDotjsRoute
  SettingsRoute: typeof SettingsRoute
  SitesSiteIdRoute: typeof SitesSiteIdRoute
  SitesNewRoute: typeof SitesNewRoute
  SitesIndexRoute: typeof SitesIndexRoute
  ApiPublicCollectRoute: typeof ApiPublicCollectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p.js': {
      id: '/p.js'
      path: '/p.js'
      fullPath: '/p.js'
      preLoaderRoute: typeof PDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/': {
      id: '/sites/'
      path: '/sites'
      fullPath: '/sites/'
      preLoaderRoute: typeof SitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/new': {
      id: '/sites/new'
      path: '/sites/new'
      fullPath: '/sites/new'
      preLoaderRoute: typeof SitesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$siteId': {
      id: '/sites/$siteId'
      path: '/sites/$siteId'
      fullPath: '/sites/$siteId'
      preLoaderRoute: typeof SitesSiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/collect': {
      id: '/api/public/collect'
      path: '/api/public/collect'
      fullPath: '/api/public/collect'
      preLoaderRoute: typeof ApiPublicCollectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  PDotjsRoute: PDotjsRoute,
  SettingsRoute: SettingsRoute,
  SitesSiteIdRoute: SitesSiteIdRoute,
  SitesNewRoute: SitesNewRoute,
  SitesIndexRoute: SitesIndexRoute,
  ApiPublicCollectRoute: ApiPublicCollectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
